services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./shared/database.sqlite:/app/shared/database.sqlite
      - ./releases:/app/releases
    restart: always
